"use client";

import React, { useState, useEffect } from "react";
import Link from "next/link";
import { supabase } from "./lib/supabase";

export default function HomePage() {
  const [inputText, setInputText] = useState("");
  const [phone, setPhone] = useState("");
  const [address, setAddress] = useState("");
  const [services, setServices] = useState("");
  const [platform, setPlatform] = useState("instagram");
  const [language, setLanguage] = useState("english");
  const [flyerStyle, setFlyerStyle] = useState("3d-agency");
  const [loading, setLoading] = useState(false);
  const [kwLoading, setKwLoading] = useState(false);
  
  const [result, setResult] = useState<string | null>(null);
  const [keywordReport, setKeywordReport] = useState<string | null>(null);
  
  const [domainName, setDomainName] = useState<string>("");
  const [autoPhone, setAutoPhone] = useState<string>("");
  const [autoAddress, setAutoAddress] = useState<string>("");
  const [autoServices, setAutoServices] = useState<string[]>([]);
  const [copied, setCopied] = useState(false);

  const [user, setUser] = useState<any>(null);
  const [credits, setCredits] = useState<number | null>(null);
  const [subId, setSubId] = useState<string | null>(null);
  const [usedCount, setUsedCount] = useState<number>(0);
  const [limitCount, setLimitCount] = useState<number>(5);

  const refreshUserCredits = async (userId: string) => {
    const { data: sub } = await supabase
      .from("subscriptions")
      .select("id, generations_limit, generations_used")
      .eq("user_id", userId)
      .maybeSingle();

    if (sub) {
      setSubId(sub.id);
      setUsedCount(sub.generations_used || 0);
      setLimitCount(sub.generations_limit || 5);
      setCredits(Math.max(0, sub.generations_limit - sub.generations_used));
    }
  };

  useEffect(() => {
    async function checkAuth() {
      const { data: { session } } = await supabase.auth.getSession();
      
      if (session?.user) {
        setUser(session.user);
        await refreshUserCredits(session.user.id);
      }
    }

    checkAuth();
  }, []);

  const handleLogout = async () => {
    await supabase.auth.signOut();
    setUser(null);
    setCredits(null);
    window.location.reload();
  };

  const handleCopy = (textToCopy: string) => {
    navigator.clipboard.writeText(textToCopy);
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  // Download PDF Functionality using Browser Print Window with Custom Stylesheet
  const handleDownloadPDF = () => {
    if (!keywordReport && !result) {
      alert("No report generated yet to export PDF!");
      return;
    }

    const reportContent = keywordReport || result || "";
    const printWindow = window.open("", "_blank");
    if (!printWindow) return;

    printWindow.document.write(`
      <html>
        <head>
          <title>${domainName.toUpperCase()} - White Label Client SEO & Growth Audit</title>
          <style>
            body { font-family: 'Segoe UI', Arial, sans-serif; padding: 40px; color: #1e293b; background: #ffffff; }
            .header { border-b: 3px solid #4f46e5; padding-bottom: 20px; margin-bottom: 30px; display: flex; justify-content: space-between; align-items: center; }
            .logo { font-size: 24px; font-weight: 900; color: #4f46e5; }
            .badge { background: #e0e7ff; color: #3730a3; font-size: 11px; font-weight: bold; padding: 4px 10px; border-radius: 6px; }
            h1, h2, h3 { color: #0f172a; }
            table { width: 100%; border-collapse: collapse; margin: 20px 0; font-size: 12px; }
            th, td { border: 1px solid #cbd5e1; padding: 10px; text-align: left; }
            th { background-color: #f1f5f9; font-weight: bold; }
            pre { white-space: pre-wrap; font-family: inherit; font-size: 13px; line-height: 1.6; }
            .footer { margin-top: 40px; border-t: 1px solid #e2e8f0; padding-top: 20px; font-size: 11px; color: #64748b; text-align: center; }
          </style>
        </head>
        <body>
          <div class="header">
            <div>
              <div class="logo">${domainName.toUpperCase()}</div>
              <div style="font-size: 12px; color: #64748b; margin-top: 4px;">Generated for Client: ${domainName} | Date: ${new Date().toLocaleDateString()}</div>
            </div>
            <div class="badge">WHITELABEL CLIENT REPORT</div>
          </div>
          <pre>${reportContent}</pre>
          <div class="footer">
            Report generated by ClipToPosts Enterprise AI Growth Suite. Confidential.
          </div>
        </body>
      </html>
    `);

    printWindow.document.close();
    printWindow.focus();
    setTimeout(() => {
      printWindow.print();
    }, 500);
  };

  // CSV / Excel Export Functionality
  const handleExportCSV = () => {
    if (!keywordReport) {
      alert("Please generate Keyword Research Report first to export CSV!");
      return;
    }

    const blob = new Blob([keywordReport], { type: "text/csv;charset=utf-8;" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.setAttribute("href", url);
    link.setAttribute("download", `${domainName}_Keyword_Audit.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  // Main Social Suite Generator
  const handleGenerate = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!inputText) return;

    if (!user) {
      alert("Please login first to generate content!");
      window.location.href = "/login";
      return;
    }

    if (credits !== null && credits <= 0) {
      alert("You have exhausted your credits! Please upgrade in Dashboard.");
      return;
    }

    setLoading(true);
    setResult(null);

    try {
      const response = await fetch("/api/generate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ 
          inputUrl: inputText, 
          platform,
          language,
          phone,
          address,
          services,
          mode: "suite"
        }),
      });

      const data = await response.json();

      if (data.success && data.text) {
        setResult(data.text);
        setDomainName(data.domainName || inputText);
        setAutoPhone(data.autoPhone);
        setAutoAddress(data.autoAddress);
        setAutoServices(data.autoServices || []);

        const newUsed = usedCount + 1;
        if (subId) {
          await supabase
            .from("subscriptions")
            .update({ generations_used: newUsed })
            .eq("id", subId);
        }
        setUsedCount(newUsed);
        setCredits(Math.max(0, limitCount - newUsed));

      } else {
        alert("Error: " + (data.error || "Something went wrong. Credits were not deducted."));
      }

    } catch (err: any) {
      console.error(err);
      alert("API Error: " + err.message);
    } finally {
      setLoading(false);
    }
  };

  // Dedicated Keyword Research & Analytics Trigger
  const handleKeywordResearch = async () => {
    if (!inputText) {
      alert("Please enter a Business Name, Keyword, or Website URL first!");
      return;
    }

    setKwLoading(true);
    setKeywordReport(null);

    try {
      const response = await fetch("/api/generate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ 
          inputUrl: inputText, 
          mode: "keywords"
        }),
      });

      const data = await response.json();

      if (data.success && data.keywordData) {
        setKeywordReport(data.keywordData);
        setDomainName(data.domainName || inputText);
      } else {
        alert("Keyword Research Error: " + (data.error || "Failed to fetch keyword analytics."));
      }

    } catch (err: any) {
      console.error(err);
      alert("API Error: " + err.message);
    } finally {
      setKwLoading(false);
    }
  };

  const getPostHookTitle = () => {
    if (!result) return "";
    const match = result.match(/• POST TITLE \/ HOOK:\s*\n?([^\n]+)/i) || result.match(/🎯 VIRAL HOOK:\s*\n?([^\n]+)/i);
    return match ? match[1].replace(/"/g, "") : `GROW YOUR BRAND WITH ${domainName.toUpperCase()}`;
  };

  const isDevotional = flyerStyle === "devotional" || domainName.includes("vedaswaram") || domainName.includes("vedas") || domainName.includes("pooja");

  return (
    <div className="min-h-screen bg-slate-950 text-slate-100 font-sans flex flex-col justify-between p-4 sm:p-6">
      
      {/* Header */}
      <header className="max-w-6xl mx-auto w-full flex items-center justify-between py-4 border-b border-slate-800">
        <h1 className="text-2xl font-black bg-gradient-to-r from-indigo-400 via-pink-400 to-amber-400 bg-clip-text text-transparent">
          ClipToPosts <span className="text-xs bg-indigo-900/80 text-indigo-300 border border-indigo-700 px-2 py-0.5 rounded-md font-mono">PRO ENTERPRISE</span>
        </h1>

        <div className="flex items-center gap-3">
          {user ? (
            <>
              <span className="text-xs bg-indigo-950 text-indigo-300 border border-indigo-800 px-3 py-1.5 rounded-xl font-bold">
                ⚡ Credits Left: {credits !== null ? credits : "..."}
              </span>
              <Link
                href="/dashboard"
                className="bg-indigo-600 hover:bg-indigo-500 text-white text-xs font-bold px-4 py-2 rounded-xl transition"
              >
                Dashboard
              </Link>
              <button
                onClick={handleLogout}
                className="text-xs text-red-400 hover:underline font-semibold"
              >
                Logout
              </button>
            </>
          ) : (
            <Link
              href="/login"
              className="bg-indigo-600 hover:bg-indigo-500 text-white font-semibold text-xs px-5 py-2 rounded-xl transition"
            >
              Login / Register
            </Link>
          )}
        </div>
      </header>

      {/* Main Content */}
      <main className="max-w-5xl mx-auto w-full text-center my-6 space-y-6">
        <h2 className="text-3xl sm:text-5xl font-extrabold text-white leading-tight">
          All-In-One Enterprise Business AI Suite
        </h2>
        <p className="text-slate-400 text-xs sm:text-sm max-w-2xl mx-auto">
          Whitelabel PDF Client Audits, Real SEO Keywords, GMB Optimization & 3D Pro Flyer Banners!
        </p>

        {/* Language & Platform Control Options */}
        <div className="flex flex-wrap items-center justify-center gap-4 pt-1 bg-slate-900/60 p-3 rounded-2xl border border-slate-800">
          <div className="flex items-center gap-2">
            <span className="text-xs font-bold text-slate-400">Language:</span>
            {[
              { id: "english", label: "English" },
              { id: "telugu", label: "తెలుగు" },
              { id: "tanglish", label: "Tanglish (Telugu-English)" },
            ].map((lang) => (
              <button
                key={lang.id}
                type="button"
                onClick={() => setLanguage(lang.id)}
                className={`px-3 py-1 rounded-lg text-xs font-semibold transition border ${
                  language === lang.id
                    ? "bg-indigo-600 text-white border-indigo-500"
                    : "bg-slate-950 text-slate-400 border-slate-800"
                }`}
              >
                {lang.label}
              </button>
            ))}
          </div>

          <div className="h-4 w-px bg-slate-800 hidden sm:block"></div>

          <div className="flex items-center gap-2">
            <span className="text-xs font-bold text-slate-400">Platform:</span>
            {[
              { id: "instagram", label: "📸 Insta" },
              { id: "linkedin", label: "💼 LinkedIn" },
              { id: "facebook", label: "📘 FB" },
              { id: "youtube", label: "🎥 YT" },
            ].map((item) => (
              <button
                key={item.id}
                type="button"
                onClick={() => setPlatform(item.id)}
                className={`px-3 py-1 rounded-lg text-xs font-bold transition border ${
                  platform === item.id
                    ? "bg-pink-600 text-white border-pink-500"
                    : "bg-slate-950 text-slate-400 border-slate-800"
                }`}
              >
                {item.label}
              </button>
            ))}
          </div>
        </div>

        {/* Business Input Form */}
        <form onSubmit={handleGenerate} className="bg-slate-900 border border-slate-800 p-5 rounded-2xl space-y-4 text-left shadow-xl">
          <div>
            <label className="text-[11px] font-bold text-slate-300 mb-1 block">Enter Business Name, Keyword, or Website URL *</label>
            <input
              type="text"
              required
              placeholder="e.g. seomynds.com or Digital Marketing Vizag or Vedaswaram"
              value={inputText}
              onChange={(e) => setInputText(e.target.value)}
              className="w-full bg-slate-950 border border-slate-800 text-white px-4 py-3 rounded-xl focus:outline-none focus:border-indigo-500 text-xs sm:text-sm"
            />
          </div>

          {/* Action Buttons Grid */}
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 pt-1">
            <button
              type="submit"
              disabled={loading}
              className="w-full bg-gradient-to-r from-indigo-600 via-purple-600 to-pink-600 hover:from-indigo-500 hover:to-pink-500 text-white font-bold py-3.5 rounded-xl transition disabled:opacity-50 text-xs sm:text-sm shadow-xl"
            >
              {loading ? `Generating ${platform.toUpperCase()} Kit...` : `🚀 Generate 3D Flyer & ${platform.toUpperCase()} Kit`}
            </button>

            {/* DEDICATED KEYWORD RESEARCH BUTTON */}
            <button
              type="button"
              onClick={handleKeywordResearch}
              disabled={kwLoading}
              className="w-full bg-gradient-to-r from-emerald-600 via-teal-600 to-cyan-600 hover:from-emerald-500 hover:to-cyan-500 text-white font-bold py-3.5 rounded-xl transition disabled:opacity-50 text-xs sm:text-sm shadow-xl border border-emerald-400/30 flex items-center justify-center gap-2"
            >
              {kwLoading ? `Auditing Live SEO Data...` : `🔍 Generate Top 10 Real SEO Keywords & Client Audit`}
            </button>
          </div>
        </form>

        {/* KEYWORD REPORT ANALYTICS BOX WITH WHITELABEL PDF & CSV BUTTONS */}
        {keywordReport && (
          <div className="bg-slate-900 border border-emerald-500/40 p-6 rounded-2xl text-left space-y-4 shadow-2xl animate-fade-in">
            <div className="flex flex-wrap items-center justify-between border-b border-slate-800 pb-3 gap-2">
              <h3 className="text-sm font-bold text-emerald-400 flex items-center gap-2">
                <span>🔍 Whitelabel Client SEO Audit & Keyword Intelligence Report</span>
                <span className="text-[10px] bg-emerald-950 text-emerald-300 border border-emerald-800 px-2 py-0.5 rounded-md font-mono">
                  LIVE SEO DATA
                </span>
              </h3>

              {/* DOWNLOAD PDF & CSV BUTTONS */}
              <div className="flex items-center gap-2">
                <button
                  onClick={handleDownloadPDF}
                  className="bg-indigo-600 hover:bg-indigo-500 text-white text-[11px] font-bold px-3 py-1.5 rounded-lg transition flex items-center gap-1 shadow border border-indigo-400"
                >
                  📄 Download Client PDF Report
                </button>

                <button
                  onClick={handleExportCSV}
                  className="bg-teal-700 hover:bg-teal-600 text-white text-[11px] font-bold px-3 py-1.5 rounded-lg transition"
                >
                  📊 Export CSV / Excel
                </button>

                <button
                  onClick={() => handleCopy(keywordReport)}
                  className="bg-slate-800 hover:bg-slate-700 text-slate-200 border border-slate-700 text-[11px] font-bold px-3 py-1.5 rounded-lg transition"
                >
                  {copied ? "Copied! ✅" : "📋 Copy Raw Text"}
                </button>
              </div>
            </div>

            <div className="text-slate-200 text-xs leading-relaxed whitespace-pre-line bg-slate-950 p-4 rounded-xl border border-slate-800 overflow-x-auto font-mono">
              {keywordReport}
            </div>
          </div>
        )}

        {/* Results Display */}
        {result && (
          <div className="mt-8 grid grid-cols-1 lg:grid-cols-12 gap-6 text-left">
            
            {/* FLYER CARD CONTAINER */}
            <div className="lg:col-span-5 bg-slate-900 border border-slate-800 p-5 rounded-2xl space-y-3 flex flex-col justify-between shadow-xl">
              <div>
                <h3 className="text-sm font-bold text-pink-400 flex items-center justify-between">
                  <span>🎨 Pro Graphic Visual Flyer</span>
                  <span className="text-[10px] bg-pink-950 text-pink-300 border border-pink-800 px-2 py-0.5 rounded-md font-normal">
                    Sample-2 Style
                  </span>
                </h3>
                <p className="text-[11px] text-slate-500 mt-1">3D Neon elements & Corporate agency layout</p>
              </div>

              {/* 3D GRAPHIC CANVAS FLYER */}
              <div 
                className={`w-full aspect-square rounded-2xl p-5 flex flex-col justify-between border shadow-2xl relative overflow-hidden ${
                  isDevotional 
                    ? "bg-gradient-to-br from-amber-950 via-slate-950 to-orange-950 border-amber-600/50 text-amber-100" 
                    : "bg-gradient-to-br from-blue-900 via-indigo-950 to-slate-950 border-blue-500/50 text-white"
                }`}
              >
                {/* 3D Neon Rings Background */}
                <div className="absolute top-10 -right-10 w-44 h-44 rounded-full border-4 border-indigo-500/30 blur-sm pointer-events-none"></div>

                {/* Header */}
                <div className="flex justify-between items-start border-b border-white/15 pb-3 relative z-10">
                  <div>
                    <span className="text-[9px] uppercase tracking-widest text-amber-400 block font-bold">WE'RE CREATIVE</span>
                    <span className="text-lg font-black tracking-wider uppercase text-white drop-shadow">
                      {domainName.toUpperCase()}
                    </span>
                  </div>
                  <div className="bg-gradient-to-r from-amber-500 to-orange-500 text-slate-950 px-3 py-1 rounded-lg font-black text-[10px] shadow-lg flex items-center gap-1">
                    <span>★ PRO AGENCY</span>
                  </div>
                </div>

                {/* Main Hook */}
                <div className="my-2 space-y-1 relative z-10">
                  <span className="text-[10px] font-bold text-indigo-300 uppercase tracking-widest block">
                    {isDevotional ? "✨ ఆధ్యాత్మిక విశేషాలు ✨" : "🔥 DIGITAL MARKETING EXPERT"}
                  </span>
                  <h3 className="text-lg sm:text-xl font-black leading-tight text-white drop-shadow-md">
                    {getPostHookTitle()}
                  </h3>
                </div>

                {/* Services Box */}
                <div className="bg-black/60 backdrop-blur-md p-3 rounded-xl border border-white/15 space-y-2 relative z-10">
                  <div className="flex justify-between items-center border-b border-white/10 pb-1.5">
                    <span className="text-[10px] font-bold text-amber-400 uppercase tracking-widest">OUR SERVICES:</span>
                    <div className="flex gap-1.5 text-xs">
                      <span className="bg-indigo-600/80 p-1 rounded-md" title="LinkedIn">💼</span>
                      <span className="bg-blue-600/80 p-1 rounded-md" title="Facebook">📘</span>
                      <span className="bg-pink-600/80 p-1 rounded-md" title="Instagram">📸</span>
                      <span className="bg-red-600/80 p-1 rounded-md" title="YouTube">🎥</span>
                    </div>
                  </div>

                  <div className="grid grid-cols-2 gap-x-2 gap-y-1 text-[10px] text-slate-200">
                    {(autoServices.length > 0 ? autoServices : ["Digital Marketing", "SEO Campaign Strategies", "Web Design & Dev", "Brand Growth"]).map((s, idx) => (
                      <div key={idx} className="flex items-center gap-1 font-semibold truncate">
                        <span className="text-amber-400">●</span> {s.trim()}
                      </div>
                    ))}
                  </div>
                </div>

                {/* Footer */}
                <div className="border-t border-white/15 pt-3 flex items-center justify-between text-[10px] relative z-10">
                  <div>
                    <span className="block text-slate-400 text-[8px]">Visit our website:</span>
                    <span className="font-bold text-white truncate max-w-[110px] block">{domainName}</span>
                  </div>

                  <div className="bg-gradient-to-r from-blue-600 to-indigo-600 text-white px-3 py-1.5 rounded-lg font-black text-[10px] shadow-lg uppercase tracking-wider border border-white/20">
                    REGISTER NOW
                  </div>

                  <div className="text-right">
                    <span className="block text-slate-400 text-[8px]">Call Us For Info:</span>
                    <span className="font-bold text-amber-300">{autoPhone}</span>
                  </div>
                </div>
              </div>

              <button
                onClick={() => alert("Capture this High-Res 3D Card to post directly on Instagram, LinkedIn, or Facebook!")}
                className="w-full bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs font-bold py-2.5 rounded-xl border border-slate-700 transition"
              >
                📸 Capture / Save Flyer Image
              </button>
            </div>

            {/* FULL CONTENT SUITE */}
            <div className="lg:col-span-7 bg-slate-900 border border-slate-800 p-5 rounded-2xl space-y-3 shadow-xl flex flex-col justify-between">
              <div>
                <div className="flex items-center justify-between">
                  <h3 className="text-sm font-bold text-indigo-400">
                    📝 Social Posts, Reel Scripts & Copy Package
                  </h3>
                  
                  <div className="flex items-center gap-2">
                    <button
                      onClick={handleDownloadPDF}
                      className="bg-indigo-600 hover:bg-indigo-500 text-white text-[11px] font-bold px-3 py-1.5 rounded-lg transition shadow"
                    >
                      📄 Export PDF
                    </button>
                    <button
                      onClick={() => handleCopy(result)}
                      className="bg-slate-800 hover:bg-slate-700 text-white text-[11px] font-bold px-3 py-1.5 rounded-lg transition"
                    >
                      {copied ? "Copied! ✅" : "📋 Copy Text"}
                    </button>
                  </div>
                </div>
                
                <p className="text-[11px] mt-1 text-slate-400">
                  Target Platform: <span className="text-pink-400 font-bold uppercase">{platform}</span> | Language: <span className="text-amber-400 uppercase">{language}</span>
                </p>
              </div>

              <div className="text-slate-200 text-xs leading-relaxed whitespace-pre-line bg-slate-950 p-4 rounded-xl border border-slate-800/80 max-h-[500px] overflow-y-auto mt-2 space-y-2">
                {result}
              </div>
            </div>

          </div>
        )}

      </main>

      {/* Footer */}
      <footer className="text-center text-xs text-slate-600 py-4 border-t border-slate-900">
        © ClipToPosts. Enterprise AI Growth Engine.
      </footer>
    </div>
  );
}
